name: main branch auto ci process script

on: # 아래 job을 실행시킬 action
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전

    steps:
      - uses: actions/checkout@v4
    
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.EC2_REMOTE_IP }} # ec2 인스턴스 ip
          username: ${{ secrets.EC2_REMOTE_USER }} # ubuntu 아이디
          password: ${{ secrets.EC2_REMOTE_PWD}}
          port: ${{ secrets.EC2_SSH_PORT }} # 접속포트번호 (보통 22)
          script: | # 실행될 스크립트
            cd ~/buddydoc/buddydoc-backend
            git fetch --all
            git reset --hard origin/main
            npm install
            npx prisma db push --schema=./src/database/prisma/schema.prisma
            npx prisma generate --schema=./src/database/prisma/schema.prisma
            pm2 reload buddydoc
